# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField()),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=75)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=45)),
                ('ignore', models.IntegerField(blank=True, null=True)),
                ('inserted_on', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canalesocial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('official', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45)),
                ('lastupdated', models.IntegerField(blank=True, null=True)),
                ('usernameid', models.TextField(blank=True)),
                ('authtoken', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'im_canalesocial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('slug', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'im_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('from_id', models.TextField(blank=True)),
                ('created_on', models.IntegerField(blank=True, null=True)),
                ('originalidcomment', models.TextField(blank=True, db_column='originalIdCommento')),
            ],
            options={
                'db_table': 'im_commento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contratto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datainizio', models.IntegerField(blank=True, null=True)),
                ('datascadenza', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'db_table': 'im_contratto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_following',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'im_mention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=120)),
                ('slug', models.CharField(blank=True, max_length=120)),
                ('descrizione', models.TextField(blank=True)),
                ('icona', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'im_metrica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('var_likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('var_comments', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('var_shares', models.IntegerField(blank=True, null=True)),
                ('img', models.TextField(blank=True)),
                ('originalidpost', models.TextField(blank=True, db_column='originalIdPost')),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('inserted_on', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.IntegerField(blank=True, null=True)),
                ('postlink', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'im_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nomeruolo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'im_ruolo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('slug', models.CharField(blank=True, max_length=45, unique=True)),
                ('likesterm', models.CharField(blank=True, max_length=40)),
                ('basepath', models.CharField(blank=True, max_length=200)),
                ('data_available', models.IntegerField(blank=True, null=True)),
                ('has_login', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_social',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=45)),
                ('password', models.CharField(blank=True, max_length=45)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(blank=True, max_length=45)),
                ('usertoken', models.CharField(blank=True, max_length=100)),
                ('lastlogin', models.IntegerField(blank=True, null=True)),
                ('tokenexpires', models.IntegerField(blank=True, null=True)),
                ('createdon', models.IntegerField(blank=True, null=True)),
                ('pic', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'im_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Valoremetrica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'im_valoremetrica',
                'managed': False,
            },
        ),
    ]
