# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_auto_20160403_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsentiment',
            name='idcomment',
            field=models.OneToOneField(db_column='idcommento', on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='sentiment.Comment'),
        ),
    ]
