# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 16:03
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0011_auto_20160413_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsentiment',
            name='sentiment_api1_en',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsentiment',
            name='sentiment_api2',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsentiment',
            name='sentiment_api2_en',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsentiment',
            name='sentiment_api3',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postsentiment',
            name='sentiment_api4',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsentiment',
            name='sentiment_api1',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
