# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 20:51
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0012_auto_20160413_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsentiment',
            name='real_sentiment',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
