# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 15:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0013_auto_20160519_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsentiment',
            name='spam',
            field=jsonfield.fields.JSONField(default=b'{"type": "", "is_spam": false}'),
        ),
    ]
