# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 09:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0014_commentsentiment_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsentiment',
            name='real_sentiment',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api1',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api1_en',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api2',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api2_en',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api3',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='commentsentiment',
            name='sentiment_api4',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
