# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0017_auto_20160530_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentapistats',
            name='accuracy_with_spam',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='sentimentapistats',
            name='accuracy',
            field=models.FloatField(default=-1),
        ),
    ]
