# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 08:41
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0018_auto_20160530_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentapistats',
            name='precision',
            field=jsonfield.fields.JSONField(default=b'{"positive": -1, "neutral": -1, "negative": -1}'),
        ),
        migrations.AddField(
            model_name='sentimentapistats',
            name='precision_with_spam',
            field=jsonfield.fields.JSONField(default=b'{"positive": -1, "neutral": -1, "negative": -1}'),
        ),
        migrations.AddField(
            model_name='sentimentapistats',
            name='recall',
            field=jsonfield.fields.JSONField(default=b'{"positive": -1, "neutral": -1, "negative": -1}'),
        ),
        migrations.AddField(
            model_name='sentimentapistats',
            name='recall_with_spam',
            field=jsonfield.fields.JSONField(default=b'{"positive": -1, "neutral": -1, "negative": -1}'),
        ),
    ]
