# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0023_auto_20160602_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentspam',
            old_name='spam_api1_ol',
            new_name='spam_api1_bare',
        ),
    ]
