# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=8, null=True)),
                ('real_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=8, null=True)),
                ('idcomment', models.ForeignKey(db_column='idcommento', on_delete=django.db.models.deletion.CASCADE, to='sentiment.Comment')),
                ('idpost', models.ForeignKey(db_column='idpost', on_delete=django.db.models.deletion.CASCADE, to='sentiment.Post')),
            ],
            options={
                'db_table': 'im_commento_sentiment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostSentiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=8, null=True)),
                ('real_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=8, null=True)),
                ('idpost', models.ForeignKey(db_column='idpost', on_delete=django.db.models.deletion.CASCADE, to='sentiment.Post')),
            ],
            options={
                'db_table': 'im_post_sentiment',
                'managed': True,
            },
        ),
    ]
