# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0009_auto_20160410_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsentiment',
            name='english_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commentsentiment',
            name='language',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
