# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0015_auto_20160527_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentApiStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_id', models.CharField(max_length=45)),
                ('accuracy', models.FloatField()),
            ],
            options={
                'db_table': 'im_sentiment_api_stats',
                'managed': True,
            },
        ),
    ]
