# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0016_sentimentapistats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentapistats',
            name='api_id',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
