# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 13:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0027_commentspam_spam_api1_with_comment_author_and_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentspam',
            name='spam_api2',
            field=jsonfield.fields.JSONField(default=b'{"type": "", "is_spam": false}'),
        ),
        migrations.AddField(
            model_name='commentspam',
            name='spam_api2_en',
            field=jsonfield.fields.JSONField(default=b'{"type": "", "is_spam": false}'),
        ),
    ]
